package net.sourceforge.symba.util.conversion.xml;

import fugeOM.service.RealizableEntityService;
import fugeOM.service.RealizableEntityServiceException;
import fugeOM.util.generatedJAXB2.FugeOMCollectionOntologyCollectionType;
import fugeOM.Collection.OntologyCollection;
import net.sourceforge.symba.ServiceLocator;
import net.sourceforge.symba.util.conversion.helper.CisbanOntologyCollectionHelper;

import javax.xml.bind.JAXBException;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.JAXBElement;
import java.io.FileNotFoundException;
import java.io.FileInputStream;
import java.net.URISyntaxException;

/**
 * This file is part of SyMBA.
 * SyMBA is covered under the GNU Lesser General Public License (LGPL).
 * Copyright (C) 2007 jointly held by Allyson Lister, Olly Shaw, and their employers.
 * To view the full licensing information for this software and ALL other files contained
 * in this distribution, please see LICENSE.txt
 *
 * This class will load all of the contents of an OntologyCollection (e.g. that generated by
 * net.sourceforge.symba.obiloader.examples.CreateFuGEOntologyCollection) into the database, for later use
 * by SyMBA templates.
 *
 * $LastChangedDate$
 * $LastChangedRevision$
 * $Author$
 * $HeadURL$
 *
 */
public class OntologyUnmarshaler {
    private final String XMLFilename;
    private final RealizableEntityService reService;

    public OntologyUnmarshaler( String inputXML ) {
        ServiceLocator serviceLocator = ServiceLocator.instance();
        this.reService = serviceLocator.getRealizableEntityService();
        this.XMLFilename = inputXML;
    }

    public void Jaxb2ToFuGE() throws JAXBException, FileNotFoundException, RealizableEntityServiceException, URISyntaxException {

        // create a JAXBContext capable of handling classes generated into
        // the fugeOM.util.generatedJAXB2 package
        JAXBContext jc = JAXBContext.newInstance( "fugeOM.util.generatedJAXB2" );

        // create an Unmarshaller
        Unmarshaller u = jc.createUnmarshaller();

        // unmarshal JUST what is normally available within an OntologyCollection
        JAXBElement<?> genericTopLevelElement = ( JAXBElement<?> ) u.unmarshal( new FileInputStream( XMLFilename ) );

        // Get the OntologyCollection root object. REMEMBER that we will not be loading the Collection, JUST its contents.
        FugeOMCollectionOntologyCollectionType collectionType = ( FugeOMCollectionOntologyCollectionType ) genericTopLevelElement
                .getValue();

        // get and store all information in the database
        CisbanOntologyCollectionHelper helper = new CisbanOntologyCollectionHelper();

        // unmarshall the jaxb object without loading the collection into the database
        OntologyCollection ontologyCollection = ( OntologyCollection ) reService
                .createDescribableOb( "fugeOM.Collection.OntologyCollection" );
        helper.unmarshalCollectionContents( collectionType, ontologyCollection );
    }

}
